// ui/src/pages/OverviewPage.svelte
<script lang="ts">
  import { createQuery } from "@tanstack/svelte-query";

  import { api, type QueueJob, type ScoutRun, type TaskListItem, type Worker } from "../lib/api";
  import { formatHeartbeat, formatRelativeTimestamp } from "../lib/format";
  import Card from "../lib/components/Card.svelte";
  import DataTable from "../lib/components/DataTable.svelte";
  import Drawer from "../lib/components/Drawer.svelte";
  import EmptyState from "../lib/components/EmptyState.svelte";
  import ErrorState from "../lib/components/ErrorState.svelte";
  import LoadingState from "../lib/components/LoadingState.svelte";
  import StatusPill from "../lib/components/StatusPill.svelte";
  import StreamLogPanel from "../lib/components/StreamLogPanel.svelte";
  import Timestamp from "../lib/components/Timestamp.svelte";

  const statusQuery = createQuery({
    queryKey: ["status"],
    queryFn: api.fetchStatus,
    refetchInterval: 5000,
  });

  const workersQuery = createQuery({
    queryKey: ["workers"],
    queryFn: api.listWorkers,
    refetchInterval: 5000,
  });

  const queueQuery = createQuery({
    queryKey: ["queue"],
    queryFn: api.listQueue,
    refetchInterval: 5000,
  });

  const reviewTasksQuery = createQuery({
    queryKey: ["tasks", "in-review-overview"],
    queryFn: () => api.listTasks({ state: "in_review", limit: 8 }),
    refetchInterval: 10000,
  });

  const scoutRunsQuery = createQuery({
    queryKey: ["scout-runs"],
    queryFn: api.listScoutRuns,
    refetchInterval: 10000,
  });

  let selectedWorkerId: string | null = null;
  let workers: Worker[] = [];
  let queueJobs: QueueJob[] = [];
  let reviewTasks: TaskListItem[] = [];
  let scoutRuns: ScoutRun[] = [];

  $: workers = ($workersQuery.data ?? []) as Worker[];
  $: queueJobs = ($queueQuery.data ?? []) as QueueJob[];
  $: reviewTasks = ($reviewTasksQuery.data ?? []) as TaskListItem[];
  $: scoutRuns = ($scoutRunsQuery.data ?? []) as ScoutRun[];
  $: selectedWorker = workers.find((worker) => worker.id === selectedWorkerId) ?? null;
</script>

<div class="space-y-6">
  {#if $statusQuery.isError}
    <ErrorState message={$statusQuery.error instanceof Error ? $statusQuery.error.message : "Failed to load overview."} />
  {/if}

  <section>
    {#if $workersQuery.isPending}
      <LoadingState label="Loading workers..." />
    {:else if workers.length === 0}
      <EmptyState label="No workers available." />
    {:else}
      <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {#each workers as worker}
          <button class="panel-surface focus-ring flex min-h-[12rem] flex-col items-start gap-4 p-4 text-left hover:bg-muted/40" on:click={() => (selectedWorkerId = worker.id)} type="button">
            <div class="flex w-full items-start justify-between gap-3">
              <div>
                <div class="text-xs uppercase tracking-[0.18em] text-muted-foreground">Worker {worker.slot}</div>
                <div class="mt-2 font-mono text-xs text-foreground">{worker.id}</div>
              </div>
              <StatusPill value={worker.status} />
            </div>

            {#if worker.currentJob}
              <div class="space-y-2 text-sm text-foreground">
                <div class="font-mono text-xs">{worker.currentJob.taskId}</div>
                <div>{worker.currentJob.action} - {worker.currentJob.repoKey}</div>
                <div class="font-mono text-xs text-muted-foreground">{worker.currentAttempt?.id ?? worker.currentAttemptId}</div>
              </div>
            {:else}
              <div class="text-sm text-muted-foreground">Idle</div>
            {/if}

            <div class="mt-auto space-y-1 text-sm text-muted-foreground">
              <div>Heartbeat {formatHeartbeat(worker.lastHeartbeatAt)}</div>
              {#if worker.currentAttempt?.startedAt}
                <div>Started {formatRelativeTimestamp(worker.currentAttempt.startedAt)}</div>
              {/if}
            </div>
          </button>
        {/each}
      </div>
    {/if}
  </section>

  <section class="grid gap-6 xl:grid-cols-3">
    <section>
      <header class="border-b border-border pb-3">
        <h2 class="m-0 text-xs uppercase tracking-[0.18em] text-muted-foreground">Needs Review</h2>
      </header>
      <div class="pt-4">
        {#if reviewTasks.length === 0}
          <EmptyState label="No tasks in review right now." />
        {:else}
          <div class="space-y-2">
            {#each reviewTasks as task}
              {@const primaryTarget = task.targets[0] ?? null}
              {@const isMultiTarget = task.targets.length > 1}
              <div class="panel-surface p-3">
                <div class="flex items-center justify-between gap-3">
                  {#if primaryTarget?.review?.pullRequestUrl}
                    <a
                      class="font-mono text-xs text-foreground underline-offset-4 hover:text-primary hover:underline"
                      href={primaryTarget.review.pullRequestUrl}
                      target="_blank"
                      rel="noreferrer"
                      on:click|stopPropagation
                    >
                      {task.id}
                    </a>
                  {:else}
                    <div class="font-mono text-xs text-foreground">{task.id}</div>
                  {/if}
                  <StatusPill value={task.state} />
                </div>
                {#if primaryTarget?.review?.pullRequestUrl}
                  <a
                    class="mt-2 block text-sm text-foreground underline-offset-4 hover:text-primary hover:underline"
                    href={primaryTarget.review.pullRequestUrl}
                    target="_blank"
                    rel="noreferrer"
                    on:click|stopPropagation
                  >
                    {task.title}
                  </a>
                {:else}
                  <div class="mt-2 text-sm text-foreground">{task.title}</div>
                {/if}
                {#if isMultiTarget}
                  <div class="mt-3 grid gap-2 sm:grid-cols-2">
                    {#each task.targets as target}
                      <div class="rounded-md border border-border/70 bg-muted/30 px-2 py-2">
                        <div class="flex items-start justify-between gap-2">
                          <div>
                            <div class="font-mono text-[11px] text-foreground">{target.repoKey}</div>
                            <div class="mt-1 font-mono text-[11px] text-muted-foreground">{target.branchName}</div>
                          </div>
                          <StatusPill value={target.status} />
                        </div>
                        {#if target.review?.pullRequestUrl}
                          <a
                            class="mt-2 inline-block font-mono text-[11px] text-foreground underline-offset-4 hover:text-primary hover:underline"
                            href={target.review.pullRequestUrl}
                            target="_blank"
                            rel="noreferrer"
                            on:click|stopPropagation
                          >
                            PR {target.review.pullRequestNumber}
                          </a>
                        {/if}
                      </div>
                    {/each}
                  </div>
                {:else}
                  <div class="mt-1 text-sm text-muted-foreground">{primaryTarget?.repoKey ?? "No repo"}</div>
                {/if}
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </section>

    <section>
      <header class="border-b border-border pb-3">
        <h2 class="m-0 text-xs uppercase tracking-[0.18em] text-muted-foreground">Active Queue</h2>
      </header>
      <div class="pt-4">
      {#if $queueQuery.isPending}
        <LoadingState label="Loading queue..." />
      {:else if queueJobs.length === 0}
        <EmptyState label="Queue is empty." />
      {:else}
        <DataTable>
          <thead class="bg-muted/40 text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
            <tr>
              <th class="px-3 py-2">Task</th>
              <th class="px-3 py-2">Action</th>
              <th class="px-3 py-2">Repo</th>
              <th class="px-3 py-2">Created</th>
            </tr>
          </thead>
          <tbody>
            {#each queueJobs.slice(0, 8) as job}
              <tr class="border-t border-border">
                <td class="px-3 py-3 font-mono text-xs text-foreground">{job.taskId}</td>
                <td class="px-3 py-3"><StatusPill value={job.action} /></td>
                <td class="px-3 py-3 text-muted-foreground">{job.repoKey}</td>
                <td class="px-3 py-3"><Timestamp value={job.createdAt} /></td>
              </tr>
            {/each}
          </tbody>
        </DataTable>
      {/if}
      </div>
    </section>

    <section>
      <header class="border-b border-border pb-3">
        <h2 class="m-0 text-xs uppercase tracking-[0.18em] text-muted-foreground">Recent Scout Runs</h2>
      </header>
      <div class="pt-4">
      {#if $scoutRunsQuery.isPending}
        <LoadingState label="Loading scout runs..." />
      {:else if scoutRuns.length === 0}
        <EmptyState label="No scout runs recorded yet." />
      {:else}
        <DataTable>
          <thead class="bg-muted/40 text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
            <tr>
              <th class="px-3 py-2">Trigger</th>
              <th class="px-3 py-2">Status</th>
              <th class="px-3 py-2">Selected</th>
              <th class="px-3 py-2">Started</th>
            </tr>
          </thead>
          <tbody>
            {#each scoutRuns.slice(0, 8) as run}
              <tr class="border-t border-border align-top">
                <td class="px-3 py-3 text-sm text-foreground">{run.triggerType}</td>
                <td class="px-3 py-3"><StatusPill value={run.status} /></td>
                <td class="px-3 py-3 text-sm text-muted-foreground">{run.selectedTaskId ? `${run.selectedAction ?? "selected"} ${run.selectedTaskId}` : "No selection"}</td>
                <td class="px-3 py-3"><Timestamp value={run.startedAt} /></td>
              </tr>
            {/each}
          </tbody>
        </DataTable>
      {/if}
      </div>
    </section>
  </section>
</div>

<Drawer open={selectedWorker !== null} title={selectedWorker ? `Worker ${selectedWorker.slot}` : "Worker"} onClose={() => (selectedWorkerId = null)}>
  {#if selectedWorker}
    <div class="space-y-6">
      <div class="grid gap-3 sm:grid-cols-2">
        <div class="panel-surface p-4">
          <div class="text-xs uppercase tracking-[0.18em] text-muted-foreground">Status</div>
          <div class="mt-3"><StatusPill value={selectedWorker.status} /></div>
        </div>
        <div class="panel-surface p-4">
          <div class="text-xs uppercase tracking-[0.18em] text-muted-foreground">Heartbeat</div>
          <div class="mt-3 text-sm text-foreground">{formatHeartbeat(selectedWorker.lastHeartbeatAt)}</div>
        </div>
      </div>

      <Card title="Worker Detail">
        <div class="space-y-2 text-sm text-muted-foreground">
          <div><span class="text-foreground">Worker ID:</span> <span class="font-mono text-xs">{selectedWorker.id}</span></div>
          <div><span class="text-foreground">Current attempt:</span> {selectedWorker.currentAttemptId ?? "idle"}</div>
          <div><span class="text-foreground">Task:</span> {selectedWorker.currentJob?.taskId ?? "-"}</div>
          <div><span class="text-foreground">Action:</span> {selectedWorker.currentJob?.action ?? "-"}</div>
          <div><span class="text-foreground">Repo:</span> {selectedWorker.currentJob?.repoKey ?? "-"}</div>
        </div>
      </Card>

      <Card title="Live Log">
        <StreamLogPanel streamUrl={`/api/workers/${selectedWorker.id}/logs/stream`} emptyMessage="Worker has not produced logs yet." includeAttemptChanges={true} />
      </Card>
    </div>
  {/if}
</Drawer>

// ui/src/pages/overview-page.tsx
import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowRightIcon, CheckCircle2Icon, GitPullRequestArrowIcon, Layers3Icon, OrbitIcon, Rows2Icon, Users2Icon } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";

import { DetailSheet } from "@/components/detail-sheet";
import { MetricCard } from "@/components/metric-card";
import { EmptyState, ErrorState, LoadingState } from "@/components/states";
import { StatusBadge } from "@/components/status-badge";
import { StreamLogPanel } from "@/components/stream-log-panel";
import { Timestamp } from "@/components/timestamp";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { api, queryKeys, type QueueJob, type TaskListItem, type Worker } from "@/lib/api";
import { formatHeartbeat, formatRelativeTimestamp, formatTimestamp, repoLabel, truncate, truncateMiddle } from "@/lib/format";

const RECENT_HISTORY_LIMIT = 6;

export function OverviewPage() {
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();
  const selectedWorkerId = searchParams.get("worker");

  const updateParams = (updates: Record<string, string | null>) => {
    const next = new URLSearchParams(searchParams);
    for (const [key, value] of Object.entries(updates)) {
      if (!value) {
        next.delete(key);
      } else {
        next.set(key, value);
      }
    }
    setSearchParams(next);
  };

  const statusQuery = useQuery({
    queryKey: queryKeys.status,
    queryFn: api.fetchStatus,
    refetchInterval: 5000,
  });

  const workersQuery = useQuery({
    queryKey: queryKeys.workers,
    queryFn: api.listWorkers,
    refetchInterval: 5000,
  });

  const queueQuery = useQuery({
    queryKey: queryKeys.queue,
    queryFn: api.listQueue,
    refetchInterval: 5000,
  });

  const reviewTasksQuery = useQuery({
    queryKey: queryKeys.tasks({ state: "in_review", limit: 8 }),
    queryFn: () => api.listTasks({ state: "in_review", limit: 8 }),
    refetchInterval: 10000,
  });

  const recentHistoryQuery = useQuery({
    queryKey: queryKeys.history({ limit: RECENT_HISTORY_LIMIT, offset: 0 }),
    queryFn: () => api.listHistory({ limit: RECENT_HISTORY_LIMIT, offset: 0 }),
    refetchInterval: 10000,
  });

  const status = statusQuery.data;
  const workers = workersQuery.data ?? [];
  const queueJobs = queueQuery.data ?? [];
  const reviewTasks = reviewTasksQuery.data ?? [];
  const recentHistory = recentHistoryQuery.data ?? [];
  const selectedWorker = workers.find((worker) => worker.id === selectedWorkerId) ?? null;

  const activeWorkers = workers.filter((worker) => worker.currentJob).length;
  const healthyWorkers = workers.filter((worker) => worker.status !== "offline").length;

  const metrics = useMemo(
    () => [
      {
        eyebrow: "Workers online",
        value: `${healthyWorkers}/${workers.length || 0}`,
        detail: activeWorkers > 0 ? `${activeWorkers} currently executing work.` : "No workers are actively executing right now.",
        icon: <Users2Icon className="size-5" />,
      },
      {
        eyebrow: "Queue depth",
        value: String(queueJobs.length),
        detail: queueJobs.length > 0 ? `Highest priority job is ${queueJobs[0]?.taskId}.` : "The execution queue is empty.",
        icon: <Rows2Icon className="size-5" />,
      },
      {
        eyebrow: "Needs review",
        value: String(reviewTasks.length),
        detail: reviewTasks.length > 0 ? `${reviewTasks[0]?.id} is the freshest review item.` : "No tasks are currently waiting on review.",
        icon: <GitPullRequestArrowIcon className="size-5" />,
      },
      {
        eyebrow: "Tracked repos",
        value: String(status?.repos.count ?? 0),
        detail: status?.repos.keys.length ? status.repos.keys.slice(0, 3).join(", ") : "No repos configured.",
        icon: <Layers3Icon className="size-5" />,
      },
    ],
    [activeWorkers, healthyWorkers, queueJobs, reviewTasks, status?.repos.count, status?.repos.keys],
  );

  return (
    <div className="space-y-6">
      <section className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]">
        <Card className="border border-border/80 bg-card/75 backdrop-blur-sm">
          <CardHeader className="border-b border-border/60">
            <CardTitle>Operational pulse</CardTitle>
            <CardDescription>Live scheduler health, workspace scope, and integration state.</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-5 pt-5 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,0.8fr)]">
            {statusQuery.isPending && !status ? (
              <LoadingState label="Loading workspace status..." />
            ) : statusQuery.isError ? (
              <ErrorState label={statusQuery.error instanceof Error ? statusQuery.error.message : "Failed to load workspace status."} />
            ) : status ? (
              <>
                <div className="space-y-4 border border-border/70 bg-background/60 p-4">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <div className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Workspace</div>
                      <div className="mt-2 text-2xl font-heading text-foreground">{status.workspace.name}</div>
                      <div className="mt-2 text-sm text-muted-foreground">{status.workspace.root}</div>
                    </div>
                    <div className="flex size-11 items-center justify-center border border-border/70 bg-primary/10 text-primary">
                      <OrbitIcon className="size-5" />
                    </div>
                  </div>
                  <div className="grid gap-3 sm:grid-cols-2">
                    <div className="border border-border/70 bg-card/80 p-3">
                      <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">Scheduler</div>
                      <div className="mt-2 flex items-center gap-2">
                        <StatusBadge value={status.scheduler.status} />
                        <span className="text-sm text-muted-foreground">{status.scheduler.workerConcurrency} slots</span>
                      </div>
                    </div>
                    <div className="border border-border/70 bg-card/80 p-3">
                      <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">Scout cadence</div>
                      <div className="mt-2 text-sm text-foreground">Every {status.scheduler.scoutPollIntervalSeconds}s</div>
                      <div className="mt-1 text-xs text-muted-foreground">
                        Next {status.scheduler.nextScoutPollAt ? formatRelativeTimestamp(status.scheduler.nextScoutPollAt) : "not scheduled"}
                      </div>
                    </div>
                  </div>
                </div>

                <div className="space-y-3">
                  {[
                    { label: "Task system", type: status.integrations.taskSystem.type, value: status.integrations.taskSystem.status },
                    { label: "Review system", type: status.integrations.reviewSystem.type, value: status.integrations.reviewSystem.status },
                    { label: "Runner", type: status.integrations.runner.type, value: status.integrations.runner.status },
                  ].map((integration) => (
                    <div key={integration.label} className="border border-border/70 bg-background/60 p-4">
                      <div className="flex items-center justify-between gap-4">
                        <div>
                          <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">{integration.label}</div>
                          <div className="mt-1 text-sm text-foreground">{integration.type}</div>
                        </div>
                        <StatusBadge value={integration.value} />
                      </div>
                    </div>
                  ))}
                </div>
              </>
            ) : null}
          </CardContent>
        </Card>

        <div className="grid gap-4 sm:grid-cols-2">
          {metrics.map((metric) => (
            <MetricCard key={metric.eyebrow} {...metric} />
          ))}
        </div>
      </section>

      <section className="space-y-4">
        <div>
          <div className="text-[11px] uppercase tracking-[0.22em] text-muted-foreground">Worker overview</div>
          <div className="mt-1 text-lg font-heading text-foreground">Live worker detail with direct log access</div>
        </div>
        {workersQuery.isPending && workers.length === 0 ? (
          <LoadingState label="Loading workers..." />
        ) : workersQuery.isError ? (
          <ErrorState label={workersQuery.error instanceof Error ? workersQuery.error.message : "Failed to load workers."} />
        ) : workers.length === 0 ? (
          <EmptyState label="No workers available." />
        ) : (
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            {workers.map((worker) => (
              <button
                key={worker.id}
                type="button"
                className="group border border-border/80 bg-card/75 p-4 text-left transition hover:-translate-y-0.5 hover:bg-card"
                onClick={() => updateParams({ worker: worker.id })}
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">Worker {worker.slot}</div>
                    <div className="mt-2 font-mono text-xs text-foreground">{worker.id}</div>
                  </div>
                  <StatusBadge value={worker.status} />
                </div>
                <div className="mt-4 min-h-16 space-y-2 text-sm text-muted-foreground">
                  {worker.currentJob ? (
                    <>
                      <div className="text-foreground">{worker.currentJob.taskId}</div>
                      <div>{worker.currentJob.action} · {worker.currentJob.repoKey}</div>
                      <div className="font-mono text-xs">{worker.currentAttempt?.id ?? worker.currentAttemptId}</div>
                    </>
                  ) : (
                    <div>Idle and ready for the next lease.</div>
                  )}
                </div>
                <div className="mt-5 flex items-center justify-between gap-3 border-t border-border/60 pt-3 text-xs text-muted-foreground">
                  <span>Heartbeat {formatHeartbeat(worker.lastHeartbeatAt)}</span>
                  <ArrowRightIcon className="size-3 transition group-hover:translate-x-0.5" />
                </div>
              </button>
            ))}
          </div>
        )}
      </section>

      <section className="grid gap-4 xl:grid-cols-3">
        <SectionCard title="Active queue" description="Up to eight queued jobs with repo and action context.">
          <QueueList jobs={queueJobs.slice(0, 8)} pending={queueQuery.isPending && queueJobs.length === 0} error={queueQuery.isError ? (queueQuery.error instanceof Error ? queueQuery.error.message : "Failed to load queue.") : null} />
        </SectionCard>

        <SectionCard title="Needs review" description="Current review-focused work summary across task targets.">
          <ReviewTaskList tasks={reviewTasks} pending={reviewTasksQuery.isPending && reviewTasks.length === 0} error={reviewTasksQuery.isError ? (reviewTasksQuery.error instanceof Error ? reviewTasksQuery.error.message : "Failed to load review tasks.") : null} />
        </SectionCard>

        <SectionCard
          title="Recent history"
          description="Compact repo history snapshots instead of scout-run activity."
          action={
            <Button type="button" variant="outline" size="sm" onClick={() => navigate("/history")}>
              View all
            </Button>
          }
        >
          {recentHistoryQuery.isPending && recentHistory.length === 0 ? (
            <LoadingState label="Loading recent history..." />
          ) : recentHistoryQuery.isError ? (
            <ErrorState label={recentHistoryQuery.error instanceof Error ? recentHistoryQuery.error.message : "Failed to load recent history."} />
          ) : recentHistory.length === 0 ? (
            <EmptyState label="No history entries recorded yet." />
          ) : (
            <div className="space-y-3">
              {recentHistory.map((record) => (
                <button
                  key={record.stepId}
                  type="button"
                  className="w-full border border-border/70 bg-background/60 p-4 text-left transition hover:border-primary/40 hover:bg-background"
                  onClick={() => navigate(`/history?selected=${record.stepId}`)}
                >
                  <div className="flex items-start justify-between gap-3">
                    <StatusBadge value={record.stage} />
                    <Timestamp value={record.createdAt} mode="relative" className="text-xs text-muted-foreground" />
                  </div>
                  <div className="mt-3 text-sm font-medium text-foreground">{record.issue}</div>
                  <div className="mt-1 text-sm text-muted-foreground">{truncate(record.summary, 96)}</div>
                  <div className="mt-3 flex flex-wrap gap-2 text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
                    {record.repos.length === 0 ? <span>No repos</span> : record.repos.map((repo) => <span key={`${record.stepId}-${repo.path}`}>{repoLabel(repo.path)}</span>)}
                  </div>
                </button>
              ))}
            </div>
          )}
        </SectionCard>
      </section>

      <DetailSheet
        open={Boolean(selectedWorker)}
        onOpenChange={(open) => {
          if (!open) {
            updateParams({ worker: null });
          }
        }}
        title={selectedWorker ? `Worker ${selectedWorker.slot}` : "Worker"}
        description="Live worker status, current lease details, and rolling log stream with attempt switches preserved."
      >
        {selectedWorker ? (
          <div className="space-y-4">
            <div className="grid gap-4 md:grid-cols-3">
              <MetricCard eyebrow="Status" value={selectedWorker.status} detail="Current worker lifecycle state." />
              <MetricCard eyebrow="Heartbeat" value={formatHeartbeat(selectedWorker.lastHeartbeatAt)} detail={formatTimestamp(selectedWorker.lastHeartbeatAt)} />
              <MetricCard eyebrow="Attempt" value={selectedWorker.currentAttemptId ? truncateMiddle(selectedWorker.currentAttemptId, 6) : "idle"} detail={selectedWorker.currentJob?.taskId ?? "No leased task."} />
            </div>

            <Card className="border border-border/80">
              <CardHeader className="border-b border-border/60">
                <CardTitle>Worker detail</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 pt-4 text-sm text-muted-foreground">
                <div className="flex items-center justify-between gap-3"><span>Worker ID</span><span className="font-mono text-xs text-foreground">{selectedWorker.id}</span></div>
                <div className="flex items-center justify-between gap-3"><span>Task</span><span className="text-foreground">{selectedWorker.currentJob?.taskId ?? "-"}</span></div>
                <div className="flex items-center justify-between gap-3"><span>Action</span><span className="text-foreground">{selectedWorker.currentJob?.action ?? "-"}</span></div>
                <div className="flex items-center justify-between gap-3"><span>Repo</span><span className="text-foreground">{selectedWorker.currentJob?.repoKey ?? "-"}</span></div>
                <div className="flex items-center justify-between gap-3"><span>Started</span><span className="text-foreground">{selectedWorker.currentAttempt?.startedAt ? formatRelativeTimestamp(selectedWorker.currentAttempt.startedAt) : "-"}</span></div>
              </CardContent>
            </Card>

            <Card className="border border-border/80">
              <CardHeader className="border-b border-border/60">
                <CardTitle>Live log</CardTitle>
                <CardDescription>Worker streams continue across attempt changes and insert explicit boundary markers.</CardDescription>
              </CardHeader>
              <CardContent className="pt-4">
                <StreamLogPanel streamUrl={`/api/workers/${selectedWorker.id}/logs/stream`} emptyMessage="Worker has not produced logs yet." includeAttemptChanges />
              </CardContent>
            </Card>
          </div>
        ) : null}
      </DetailSheet>
    </div>
  );
}

type SectionCardProps = {
  title: string;
  description: string;
  children: React.ReactNode;
  action?: React.ReactNode;
};

function SectionCard({ title, description, children, action }: SectionCardProps) {
  return (
    <Card className="border border-border/80 bg-card/75 backdrop-blur-sm">
      <CardHeader className="border-b border-border/60">
        <div className="flex items-start justify-between gap-4">
          <div>
            <CardTitle>{title}</CardTitle>
            <CardDescription>{description}</CardDescription>
          </div>
          {action}
        </div>
      </CardHeader>
      <CardContent className="pt-4">{children}</CardContent>
    </Card>
  );
}

type QueueListProps = {
  jobs: QueueJob[];
  pending: boolean;
  error: string | null;
};

function QueueList({ jobs, pending, error }: QueueListProps) {
  if (pending) {
    return <LoadingState label="Loading queue..." />;
  }

  if (error) {
    return <ErrorState label={error} />;
  }

  if (jobs.length === 0) {
    return <EmptyState label="Queue is empty." />;
  }

  return (
    <div className="space-y-3">
      {jobs.map((job) => (
        <div key={job.id} className="border border-border/70 bg-background/60 p-4">
          <div className="flex items-start justify-between gap-3">
            <div>
              <div className="font-mono text-xs text-foreground">{job.taskId}</div>
              <div className="mt-1 text-sm text-muted-foreground">{job.repoKey}</div>
            </div>
            <StatusBadge value={job.action} />
          </div>
          <div className="mt-3 flex items-center justify-between gap-3 text-xs text-muted-foreground">
            <span>Priority {job.priorityRank}</span>
            <Timestamp value={job.createdAt} mode="relative" className="text-xs text-muted-foreground" />
          </div>
        </div>
      ))}
    </div>
  );
}

type ReviewTaskListProps = {
  tasks: TaskListItem[];
  pending: boolean;
  error: string | null;
};

function ReviewTaskList({ tasks, pending, error }: ReviewTaskListProps) {
  if (pending) {
    return <LoadingState label="Loading review tasks..." />;
  }

  if (error) {
    return <ErrorState label={error} />;
  }

  if (tasks.length === 0) {
    return <EmptyState label="No tasks are in review right now." />;
  }

  return (
    <div className="space-y-3">
      {tasks.map((task) => {
        const primaryTarget = task.targets[0] ?? null;
        const multiTarget = task.targets.length > 1;

        return (
          <div key={task.id} className="border border-border/70 bg-background/60 p-4">
            <div className="flex items-center justify-between gap-3">
              <div className="font-mono text-xs text-foreground">{task.id}</div>
              <StatusBadge value={task.state} />
            </div>
            <div className="mt-2 text-sm text-foreground">{task.title}</div>
            {multiTarget ? (
              <div className="mt-3 grid gap-2 sm:grid-cols-2">
                {task.targets.map((target) => (
                  <div key={target.id} className="border border-border/70 bg-card/60 p-3">
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <div className="font-mono text-[11px] text-foreground">{target.repoKey}</div>
                        <div className="mt-1 font-mono text-[11px] text-muted-foreground">{target.branchName}</div>
                      </div>
                      <StatusBadge value={target.status} />
                    </div>
                    {target.review?.pullRequestUrl ? (
                      <a className="mt-2 inline-flex items-center gap-1 text-[11px] text-primary hover:underline" href={target.review.pullRequestUrl} rel="noreferrer" target="_blank">
                        PR {target.review.pullRequestNumber}
                      </a>
                    ) : null}
                  </div>
                ))}
              </div>
            ) : (
              <div className="mt-3 flex items-center justify-between gap-3 text-sm text-muted-foreground">
                <span>{primaryTarget?.repoKey ?? task.repo ?? "No repo"}</span>
                {primaryTarget?.review?.pullRequestUrl ? (
                  <a className="inline-flex items-center gap-1 text-primary hover:underline" href={primaryTarget.review.pullRequestUrl} rel="noreferrer" target="_blank">
                    PR {primaryTarget.review.pullRequestNumber}
                  </a>
                ) : null}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
